### ISSUE TITLE
Mark as deprecated

### ISSUE THREAD

**Issue by denis-soundcloud** [denisdefreyne/fast-aleck#12]
This project is no longer in development and should be clearly marked as such in the README.
1. Typographical enhancement is an intrinsically difficult task, and I believe it cannot be done reliably.
2. Fast Aleck is unfinished, as there are still a bunch of failing tests cases, which I attribute to the same cause as point 1. It is also not as fast as I had hoped it to be (although with more work, this could be solved).
3. I don’t use any typographical enhancement tool anymore anyway, because I type the proper characters (smart quotes, em dashes, ellipses) manually.

**Comment by denisdefreyne** [comment]
Done in 1d97d1783ea3701bb6f5d5e5a6286f1e8914c8a3.
